# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Masterprojekt\03_Production\Maya\scripts\assetIO\assetIOWidget.ui'
#
# Created: Wed May 30 10:05:54 2018
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_AssetIO(object):
    def setupUi(self, AssetIO):
        AssetIO.setObjectName("AssetIO")
        AssetIO.resize(574, 474)
        self.centralwidget = QtWidgets.QWidget(AssetIO)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.assetIO_tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.assetIO_tabWidget.setEnabled(True)
        self.assetIO_tabWidget.setStyleSheet("QTabBar::tab { height: 25px; width: 100%; }")
        self.assetIO_tabWidget.setObjectName("assetIO_tabWidget")
        self.exportTab = QtWidgets.QWidget()
        self.exportTab.setObjectName("exportTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.exportTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.export_assetDetails_grpBox = QtWidgets.QGroupBox(self.exportTab)
        self.export_assetDetails_grpBox.setTitle("")
        self.export_assetDetails_grpBox.setObjectName("export_assetDetails_grpBox")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.export_assetDetails_grpBox)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.exportAssetName_layout = QtWidgets.QHBoxLayout()
        self.exportAssetName_layout.setObjectName("exportAssetName_layout")
        self.eportAssetName_label = QtWidgets.QLabel(self.export_assetDetails_grpBox)
        self.eportAssetName_label.setMargin(0)
        self.eportAssetName_label.setObjectName("eportAssetName_label")
        self.exportAssetName_layout.addWidget(self.eportAssetName_label)
        self.exportAssetName_input = QtWidgets.QLineEdit(self.export_assetDetails_grpBox)
        self.exportAssetName_input.setMinimumSize(QtCore.QSize(250, 0))
        self.exportAssetName_input.setObjectName("exportAssetName_input")
        self.exportAssetName_layout.addWidget(self.exportAssetName_input)
        self.exportAssetName_browseButton = QtWidgets.QPushButton(self.export_assetDetails_grpBox)
        self.exportAssetName_browseButton.setObjectName("exportAssetName_browseButton")
        self.exportAssetName_layout.addWidget(self.exportAssetName_browseButton)
        self.verticalLayout_10.addLayout(self.exportAssetName_layout)
        self.exportCategory_layout = QtWidgets.QHBoxLayout()
        self.exportCategory_layout.setObjectName("exportCategory_layout")
        self.exportCategory_label = QtWidgets.QLabel(self.export_assetDetails_grpBox)
        self.exportCategory_label.setObjectName("exportCategory_label")
        self.exportCategory_layout.addWidget(self.exportCategory_label)
        self.exportCategory_CB = QtWidgets.QComboBox(self.export_assetDetails_grpBox)
        self.exportCategory_CB.setObjectName("exportCategory_CB")
        self.exportCategory_layout.addWidget(self.exportCategory_CB)
        self.exportCategoryAdd_button = QtWidgets.QPushButton(self.export_assetDetails_grpBox)
        self.exportCategoryAdd_button.setObjectName("exportCategoryAdd_button")
        self.exportCategory_layout.addWidget(self.exportCategoryAdd_button)
        self.verticalLayout_10.addLayout(self.exportCategory_layout)
        self.exportFrameSel_layout = QtWidgets.QHBoxLayout()
        self.exportFrameSel_layout.setObjectName("exportFrameSel_layout")
        self.exportFrameSel_checkbox = QtWidgets.QCheckBox(self.export_assetDetails_grpBox)
        self.exportFrameSel_checkbox.setChecked(True)
        self.exportFrameSel_checkbox.setObjectName("exportFrameSel_checkbox")
        self.exportFrameSel_layout.addWidget(self.exportFrameSel_checkbox)
        self.export_breakRef_chkbox = QtWidgets.QCheckBox(self.export_assetDetails_grpBox)
        self.export_breakRef_chkbox.setObjectName("export_breakRef_chkbox")
        self.exportFrameSel_layout.addWidget(self.export_breakRef_chkbox)
        self.verticalLayout_10.addLayout(self.exportFrameSel_layout)
        self.verticalLayout_3.addWidget(self.export_assetDetails_grpBox)
        self.exportDescription_grpBox = QtWidgets.QGroupBox(self.exportTab)
        self.exportDescription_grpBox.setObjectName("exportDescription_grpBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.exportDescription_grpBox)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.exportDescription_textEdit = QtWidgets.QTextEdit(self.exportDescription_grpBox)
        self.exportDescription_textEdit.setObjectName("exportDescription_textEdit")
        self.verticalLayout_7.addWidget(self.exportDescription_textEdit)
        self.verticalLayout_3.addWidget(self.exportDescription_grpBox)
        self.exportButtons_grpBox = QtWidgets.QGroupBox(self.exportTab)
        self.exportButtons_grpBox.setTitle("")
        self.exportButtons_grpBox.setObjectName("exportButtons_grpBox")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.exportButtons_grpBox)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.exportAll_button = QtWidgets.QPushButton(self.exportButtons_grpBox)
        self.exportAll_button.setObjectName("exportAll_button")
        self.horizontalLayout_5.addWidget(self.exportAll_button)
        self.exportSelected_button = QtWidgets.QPushButton(self.exportButtons_grpBox)
        self.exportSelected_button.setObjectName("exportSelected_button")
        self.horizontalLayout_5.addWidget(self.exportSelected_button)
        self.verticalLayout_3.addWidget(self.exportButtons_grpBox)
        self.assetIO_tabWidget.addTab(self.exportTab, "")
        self.importTab = QtWidgets.QWidget()
        self.importTab.setObjectName("importTab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.importTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.importSearch_layout = QtWidgets.QHBoxLayout()
        self.importSearch_layout.setObjectName("importSearch_layout")
        self.importCategory_label = QtWidgets.QLabel(self.importTab)
        self.importCategory_label.setObjectName("importCategory_label")
        self.importSearch_layout.addWidget(self.importCategory_label)
        self.importCategory_cBox = QtWidgets.QComboBox(self.importTab)
        self.importCategory_cBox.setObjectName("importCategory_cBox")
        self.importSearch_layout.addWidget(self.importCategory_cBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.importSearch_layout.addItem(spacerItem)
        self.importSearch_label = QtWidgets.QLabel(self.importTab)
        self.importSearch_label.setObjectName("importSearch_label")
        self.importSearch_layout.addWidget(self.importSearch_label)
        self.importSearch_lineEdit = QtWidgets.QLineEdit(self.importTab)
        self.importSearch_lineEdit.setObjectName("importSearch_lineEdit")
        self.importSearch_layout.addWidget(self.importSearch_lineEdit)
        self.verticalLayout.addLayout(self.importSearch_layout)
        self.importBrowser_layout = QtWidgets.QHBoxLayout()
        self.importBrowser_layout.setObjectName("importBrowser_layout")
        self.importList = QtWidgets.QListWidget(self.importTab)
        self.importList.setObjectName("importList")
        self.importBrowser_layout.addWidget(self.importList)
        self.importProperties_grpBox = QtWidgets.QGroupBox(self.importTab)
        self.importProperties_grpBox.setMinimumSize(QtCore.QSize(150, 0))
        self.importProperties_grpBox.setObjectName("importProperties_grpBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.importProperties_grpBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.importProperties_icon = QtWidgets.QLabel(self.importProperties_grpBox)
        self.importProperties_icon.setText("")
        self.importProperties_icon.setPixmap(QtGui.QPixmap("assetDefaultIcon.png"))
        self.importProperties_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.importProperties_icon.setObjectName("importProperties_icon")
        self.verticalLayout_4.addWidget(self.importProperties_icon)
        self.importProperties_layout = QtWidgets.QFormLayout()
        self.importProperties_layout.setObjectName("importProperties_layout")
        self.importPropertiesName_label = QtWidgets.QLabel(self.importProperties_grpBox)
        self.importPropertiesName_label.setObjectName("importPropertiesName_label")
        self.importProperties_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.importPropertiesName_label)
        self.importPropertiesName_display = QtWidgets.QLabel(self.importProperties_grpBox)
        self.importPropertiesName_display.setObjectName("importPropertiesName_display")
        self.importProperties_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.importPropertiesName_display)
        self.importPropertiesCategory_label = QtWidgets.QLabel(self.importProperties_grpBox)
        self.importPropertiesCategory_label.setObjectName("importPropertiesCategory_label")
        self.importProperties_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.importPropertiesCategory_label)
        self.importPropertiesCategory_display = QtWidgets.QLabel(self.importProperties_grpBox)
        self.importPropertiesCategory_display.setObjectName("importPropertiesCategory_display")
        self.importProperties_layout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.importPropertiesCategory_display)
        self.importPropertiesDescription_label = QtWidgets.QLabel(self.importProperties_grpBox)
        self.importPropertiesDescription_label.setObjectName("importPropertiesDescription_label")
        self.importProperties_layout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.importPropertiesDescription_label)
        self.importPropertiesDescription_textEdit = QtWidgets.QTextEdit(self.importProperties_grpBox)
        self.importPropertiesDescription_textEdit.setReadOnly(True)
        self.importPropertiesDescription_textEdit.setObjectName("importPropertiesDescription_textEdit")
        self.importProperties_layout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.importPropertiesDescription_textEdit)
        self.importPropertiesMod_label = QtWidgets.QLabel(self.importProperties_grpBox)
        self.importPropertiesMod_label.setObjectName("importPropertiesMod_label")
        self.importProperties_layout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.importPropertiesMod_label)
        self.importPropertiesMod_display = QtWidgets.QLabel(self.importProperties_grpBox)
        self.importPropertiesMod_display.setObjectName("importPropertiesMod_display")
        self.importProperties_layout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.importPropertiesMod_display)
        self.verticalLayout_4.addLayout(self.importProperties_layout)
        self.importProperties_chkbox_layout = QtWidgets.QHBoxLayout()
        self.importProperties_chkbox_layout.setObjectName("importProperties_chkbox_layout")
        self.importProperties_locator_checkbox = QtWidgets.QCheckBox(self.importProperties_grpBox)
        self.importProperties_locator_checkbox.setObjectName("importProperties_locator_checkbox")
        self.importProperties_chkbox_layout.addWidget(self.importProperties_locator_checkbox)
        self.importProperties_selectable_checkbox = QtWidgets.QCheckBox(self.importProperties_grpBox)
        self.importProperties_selectable_checkbox.setEnabled(False)
        self.importProperties_selectable_checkbox.setObjectName("importProperties_selectable_checkbox")
        self.importProperties_chkbox_layout.addWidget(self.importProperties_selectable_checkbox)
        self.verticalLayout_4.addLayout(self.importProperties_chkbox_layout)
        self.importBrowser_layout.addWidget(self.importProperties_grpBox)
        self.verticalLayout.addLayout(self.importBrowser_layout)
        self.importButtons_layout = QtWidgets.QHBoxLayout()
        self.importButtons_layout.setObjectName("importButtons_layout")
        self.importImport_button = QtWidgets.QPushButton(self.importTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.importImport_button.sizePolicy().hasHeightForWidth())
        self.importImport_button.setSizePolicy(sizePolicy)
        self.importImport_button.setObjectName("importImport_button")
        self.importButtons_layout.addWidget(self.importImport_button)
        self.importReference_button = QtWidgets.QPushButton(self.importTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.importReference_button.sizePolicy().hasHeightForWidth())
        self.importReference_button.setSizePolicy(sizePolicy)
        self.importReference_button.setObjectName("importReference_button")
        self.importButtons_layout.addWidget(self.importReference_button)
        self.verticalLayout.addLayout(self.importButtons_layout)
        self.assetIO_tabWidget.addTab(self.importTab, "")
        self.ManageTab = QtWidgets.QWidget()
        self.ManageTab.setObjectName("ManageTab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.ManageTab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.manage_dupliRemove_layout = QtWidgets.QHBoxLayout()
        self.manage_dupliRemove_layout.setObjectName("manage_dupliRemove_layout")
        self.manage_duplicateSel_btn = QtWidgets.QPushButton(self.ManageTab)
        self.manage_duplicateSel_btn.setObjectName("manage_duplicateSel_btn")
        self.manage_dupliRemove_layout.addWidget(self.manage_duplicateSel_btn)
        self.manage_deleteSel_btn = QtWidgets.QPushButton(self.ManageTab)
        self.manage_deleteSel_btn.setObjectName("manage_deleteSel_btn")
        self.manage_dupliRemove_layout.addWidget(self.manage_deleteSel_btn)
        self.verticalLayout_6.addLayout(self.manage_dupliRemove_layout)
        self.manage_referenceObjects_list = QtWidgets.QListWidget(self.ManageTab)
        self.manage_referenceObjects_list.setObjectName("manage_referenceObjects_list")
        self.verticalLayout_6.addWidget(self.manage_referenceObjects_list)
        self.assetIO_tabWidget.addTab(self.ManageTab, "")
        self.verticalLayout_2.addWidget(self.assetIO_tabWidget)
        AssetIO.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AssetIO)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 574, 21))
        self.menubar.setObjectName("menubar")
        AssetIO.setMenuBar(self.menubar)

        self.retranslateUi(AssetIO)
        self.assetIO_tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(AssetIO)

    def retranslateUi(self, AssetIO):
        AssetIO.setWindowTitle(QtWidgets.QApplication.translate("AssetIO", "Asset IO", None, -1))
        self.eportAssetName_label.setText(QtWidgets.QApplication.translate("AssetIO", "Asset Name", None, -1))
        self.exportAssetName_browseButton.setText(QtWidgets.QApplication.translate("AssetIO", "Browse", None, -1))
        self.exportCategory_label.setText(QtWidgets.QApplication.translate("AssetIO", "Category", None, -1))
        self.exportCategoryAdd_button.setText(QtWidgets.QApplication.translate("AssetIO", "Add", None, -1))
        self.exportFrameSel_checkbox.setText(QtWidgets.QApplication.translate("AssetIO", "Auto Frame Selected", None, -1))
        self.export_breakRef_chkbox.setText(QtWidgets.QApplication.translate("AssetIO", "Break References", None, -1))
        self.exportDescription_grpBox.setTitle(QtWidgets.QApplication.translate("AssetIO", "Description", None, -1))
        self.exportAll_button.setText(QtWidgets.QApplication.translate("AssetIO", "Export All", None, -1))
        self.exportSelected_button.setText(QtWidgets.QApplication.translate("AssetIO", "Export Selected", None, -1))
        self.assetIO_tabWidget.setTabText(self.assetIO_tabWidget.indexOf(self.exportTab), QtWidgets.QApplication.translate("AssetIO", "Export", None, -1))
        self.importCategory_label.setText(QtWidgets.QApplication.translate("AssetIO", "Category Filter", None, -1))
        self.importSearch_label.setText(QtWidgets.QApplication.translate("AssetIO", "Search", None, -1))
        self.importProperties_grpBox.setTitle(QtWidgets.QApplication.translate("AssetIO", "Properties", None, -1))
        self.importPropertiesName_label.setText(QtWidgets.QApplication.translate("AssetIO", "Name", None, -1))
        self.importPropertiesName_display.setText(QtWidgets.QApplication.translate("AssetIO", "-", None, -1))
        self.importPropertiesCategory_label.setText(QtWidgets.QApplication.translate("AssetIO", "Category", None, -1))
        self.importPropertiesCategory_display.setText(QtWidgets.QApplication.translate("AssetIO", "-", None, -1))
        self.importPropertiesDescription_label.setText(QtWidgets.QApplication.translate("AssetIO", "Description", None, -1))
        self.importPropertiesMod_label.setText(QtWidgets.QApplication.translate("AssetIO", "Last Modified", None, -1))
        self.importPropertiesMod_display.setText(QtWidgets.QApplication.translate("AssetIO", "-", None, -1))
        self.importProperties_locator_checkbox.setText(QtWidgets.QApplication.translate("AssetIO", "Group to Locator", None, -1))
        self.importProperties_selectable_checkbox.setText(QtWidgets.QApplication.translate("AssetIO", "Selectable", None, -1))
        self.importImport_button.setText(QtWidgets.QApplication.translate("AssetIO", "Import", None, -1))
        self.importReference_button.setText(QtWidgets.QApplication.translate("AssetIO", "Reference", None, -1))
        self.assetIO_tabWidget.setTabText(self.assetIO_tabWidget.indexOf(self.importTab), QtWidgets.QApplication.translate("AssetIO", "Import", None, -1))
        self.manage_duplicateSel_btn.setText(QtWidgets.QApplication.translate("AssetIO", "Duplicate Selected", None, -1))
        self.manage_deleteSel_btn.setText(QtWidgets.QApplication.translate("AssetIO", "Delete Selected", None, -1))
        self.assetIO_tabWidget.setTabText(self.assetIO_tabWidget.indexOf(self.ManageTab), QtWidgets.QApplication.translate("AssetIO", "Manage", None, -1))

