# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\chris\Nextcloud\03_Production\Maya\scripts\sceneChecker\mainView.ui'
#
# Created: Fri Oct 12 19:34:53 2018
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_sceneChecker(object):
    def setupUi(self, sceneChecker):
        sceneChecker.setObjectName("sceneChecker")
        sceneChecker.resize(335, 195)
        self.main_widget = QtWidgets.QWidget(sceneChecker)
        self.main_widget.setObjectName("main_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.main_widget)
        self.verticalLayout.setContentsMargins(-1, 5, -1, 1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkScene_btn = QtWidgets.QPushButton(self.main_widget)
        self.checkScene_btn.setObjectName("checkScene_btn")
        self.verticalLayout.addWidget(self.checkScene_btn)
        self.proxyTexture_layout = QtWidgets.QHBoxLayout()
        self.proxyTexture_layout.setObjectName("proxyTexture_layout")
        self.proxyTexture_label = QtWidgets.QLabel(self.main_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.proxyTexture_label.sizePolicy().hasHeightForWidth())
        self.proxyTexture_label.setSizePolicy(sizePolicy)
        self.proxyTexture_label.setObjectName("proxyTexture_label")
        self.proxyTexture_layout.addWidget(self.proxyTexture_label)
        self.proxyTexture_message = QtWidgets.QLabel(self.main_widget)
        self.proxyTexture_message.setStyleSheet("")
        self.proxyTexture_message.setObjectName("proxyTexture_message")
        self.proxyTexture_layout.addWidget(self.proxyTexture_message)
        self.verticalLayout.addLayout(self.proxyTexture_layout)
        self.openSubdiv_layout = QtWidgets.QHBoxLayout()
        self.openSubdiv_layout.setObjectName("openSubdiv_layout")
        self.openSubdiv_label = QtWidgets.QLabel(self.main_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openSubdiv_label.sizePolicy().hasHeightForWidth())
        self.openSubdiv_label.setSizePolicy(sizePolicy)
        self.openSubdiv_label.setObjectName("openSubdiv_label")
        self.openSubdiv_layout.addWidget(self.openSubdiv_label)
        self.openSubdiv_count = QtWidgets.QLabel(self.main_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openSubdiv_count.sizePolicy().hasHeightForWidth())
        self.openSubdiv_count.setSizePolicy(sizePolicy)
        self.openSubdiv_count.setObjectName("openSubdiv_count")
        self.openSubdiv_layout.addWidget(self.openSubdiv_count)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.openSubdiv_layout.addItem(spacerItem)
        self.openSubdiv_select_btn = QtWidgets.QPushButton(self.main_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openSubdiv_select_btn.sizePolicy().hasHeightForWidth())
        self.openSubdiv_select_btn.setSizePolicy(sizePolicy)
        self.openSubdiv_select_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.openSubdiv_select_btn.setObjectName("openSubdiv_select_btn")
        self.openSubdiv_layout.addWidget(self.openSubdiv_select_btn)
        self.verticalLayout.addLayout(self.openSubdiv_layout)
        self.ShadowCasting_layout = QtWidgets.QHBoxLayout()
        self.ShadowCasting_layout.setObjectName("ShadowCasting_layout")
        self.shadowCasting_label = QtWidgets.QLabel(self.main_widget)
        self.shadowCasting_label.setObjectName("shadowCasting_label")
        self.ShadowCasting_layout.addWidget(self.shadowCasting_label)
        self.shadowCasting_count = QtWidgets.QLabel(self.main_widget)
        self.shadowCasting_count.setObjectName("shadowCasting_count")
        self.ShadowCasting_layout.addWidget(self.shadowCasting_count)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.ShadowCasting_layout.addItem(spacerItem1)
        self.shadowCasting_select_btn = QtWidgets.QPushButton(self.main_widget)
        self.shadowCasting_select_btn.setObjectName("shadowCasting_select_btn")
        self.ShadowCasting_layout.addWidget(self.shadowCasting_select_btn)
        self.verticalLayout.addLayout(self.ShadowCasting_layout)
        self.renderElements_layout = QtWidgets.QHBoxLayout()
        self.renderElements_layout.setObjectName("renderElements_layout")
        self.renderElements_label = QtWidgets.QLabel(self.main_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.renderElements_label.sizePolicy().hasHeightForWidth())
        self.renderElements_label.setSizePolicy(sizePolicy)
        self.renderElements_label.setObjectName("renderElements_label")
        self.renderElements_layout.addWidget(self.renderElements_label)
        self.renderElements_count = QtWidgets.QLabel(self.main_widget)
        self.renderElements_count.setObjectName("renderElements_count")
        self.renderElements_layout.addWidget(self.renderElements_count)
        self.verticalLayout.addLayout(self.renderElements_layout)
        self.renderSettings_layout = QtWidgets.QHBoxLayout()
        self.renderSettings_layout.setObjectName("renderSettings_layout")
        self.renderSettings_label = QtWidgets.QLabel(self.main_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.renderSettings_label.sizePolicy().hasHeightForWidth())
        self.renderSettings_label.setSizePolicy(sizePolicy)
        self.renderSettings_label.setObjectName("renderSettings_label")
        self.renderSettings_layout.addWidget(self.renderSettings_label)
        self.renderSettings_message = QtWidgets.QLabel(self.main_widget)
        self.renderSettings_message.setObjectName("renderSettings_message")
        self.renderSettings_layout.addWidget(self.renderSettings_message)
        self.verticalLayout.addLayout(self.renderSettings_layout)
        sceneChecker.setCentralWidget(self.main_widget)
        self.menubar = QtWidgets.QMenuBar(sceneChecker)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 335, 21))
        self.menubar.setObjectName("menubar")
        sceneChecker.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(sceneChecker)
        self.statusbar.setObjectName("statusbar")
        sceneChecker.setStatusBar(self.statusbar)

        self.retranslateUi(sceneChecker)
        QtCore.QMetaObject.connectSlotsByName(sceneChecker)

    def retranslateUi(self, sceneChecker):
        sceneChecker.setWindowTitle(QtWidgets.QApplication.translate("sceneChecker", "Scene Checker", None, -1))
        self.checkScene_btn.setText(QtWidgets.QApplication.translate("sceneChecker", "Check Scene", None, -1))
        self.proxyTexture_label.setText(QtWidgets.QApplication.translate("sceneChecker", "Proxy Textures:", None, -1))
        self.proxyTexture_message.setText(QtWidgets.QApplication.translate("sceneChecker", "-", None, -1))
        self.openSubdiv_label.setText(QtWidgets.QApplication.translate("sceneChecker", "Objects without subdiv:", None, -1))
        self.openSubdiv_count.setText(QtWidgets.QApplication.translate("sceneChecker", "-", None, -1))
        self.openSubdiv_select_btn.setText(QtWidgets.QApplication.translate("sceneChecker", "Select", None, -1))
        self.shadowCasting_label.setText(QtWidgets.QApplication.translate("sceneChecker", "Objects without shadow: ", None, -1))
        self.shadowCasting_count.setText(QtWidgets.QApplication.translate("sceneChecker", "-", None, -1))
        self.shadowCasting_select_btn.setText(QtWidgets.QApplication.translate("sceneChecker", "Select", None, -1))
        self.renderElements_label.setText(QtWidgets.QApplication.translate("sceneChecker", "Render Element Count (AOVs):", None, -1))
        self.renderElements_count.setText(QtWidgets.QApplication.translate("sceneChecker", "-", None, -1))
        self.renderSettings_label.setText(QtWidgets.QApplication.translate("sceneChecker", "Render Settings: ", None, -1))
        self.renderSettings_message.setText(QtWidgets.QApplication.translate("sceneChecker", "-", None, -1))

